# Generated by Django 3.0.6 on 2020-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_booktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookAuthor',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
