# Generated by Django 3.0.6 on 2020-11-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20201105_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.FileField(upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
