# Generated by Django 3.0.6 on 2020-11-10 17:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20201106_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
