# Generated by Django 3.0.6 on 2020-11-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
