# Generated by Django 3.0.6 on 2020-11-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bookISBN',
        ),
    ]
