# Generated by Django 3.0.6 on 2020-11-19 15:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_review_bookisbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioImage', models.ImageField(null=True, upload_to='images/')),
                ('bioCaption', models.CharField(max_length=64)),
                ('quote', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
