# Generated by Django 3.0.6 on 2020-11-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
