# Generated by Django 3.0.6 on 2020-11-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_biocaption_bioparagraph_biopicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BioCaption',
        ),
        migrations.AddField(
            model_name='biopicture',
            name='caption',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biopicture',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
