# Generated by Django 3.0.6 on 2020-11-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20201119_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookAuthorLastName',
            field=models.CharField(default='', max_length=64),
        ),
    ]
